[package]
name = "tan_convert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tan = { path = "../tan", version = "0.3" }
tan_fmt = { path = "../tan_fmt", version = "0.3" }
